### ISSUE TITLE
option to add a trim command and no auto trim on save?

### ISSUE THREAD

**Issue by rtgiskard** [cappyzawa/trim.nvim#15]
I'd like to option to disable auto trim on write, as this may add extra modification for some text file and is unnecessary for most of the time. Provide a command is better for my case.

**Comment by cappyzawa** [comment]
> Provide a command is better for my case.

Even without providing a new command with this plugin, you can avoid trimming when writing by executing `:noa w`.

**Comment by rtgiskard** [comment]
I have read this, but an option to disable auto trim on write will be good, so that I can keep the more convenient `:w`  for the default writing instead of `:noa w` every time to write the text file.
 
And when it's disabled, provide a user command so that I can format whenever I want will be great.

**Comment by cappyzawa** [comment]
Thanks for your explanation. I understood it.

Your opinion is good 👍 
I will try to work on it this week.

**Comment by cappyzawa** [comment]
@rtgiskard 
I added `:TrimToggle` command.
I'd be happy to give it a try.
