### ISSUE TITLE
option to not highlight whitespace between the end of the line and the current cursor position

### ISSUE THREAD

**Issue by bbkane** [cappyzawa/trim.nvim#26]
I'm finding this plugin very useful, thanks for making it!

When typing, whenever I type space, it highlights it red before I start typing the next word. I find this kind of jarring; is there a way to avoid it? I still want to highlight end of line whitespace that's not right beforey cursor

**Comment by cappyzawa** [comment]
Thanks for your report!
I fixed in https://github.com/cappyzawa/trim.nvim/commit/7dc35b9e61b9f77f475807a2be6fe8115a12d81c.
