### ISSUE TITLE
Trimmer executing mutliple times?

### ISSUE THREAD

**Issue by vzytoi** [cappyzawa/trim.nvim#5]
First of all, sorry for asking you that much maintenance for an as little plugin.
I hope that I'm making a mistake but maybe the trimmer is executing multiple times?
Tell me if I'm wrong
```
local vim = vim
local api = vim.api
local cfg = require'trim.config'

local c = 0

local trimmer = {
  trim = function ()
    local save = vim.fn.winsaveview()
    for _, v in pairs(cfg.patterns) do
        c = c + 1
      api.nvim_exec(string.format("silent! %s", v), false)
    end
    vim.fn.winrestview(save)
        print(c)
  end
}

return trimmer
```
Ouput : 
````
4
8
12
16
20
````

Have a nice day!

**Comment by cappyzawa** [comment]
hmmm...

In my environment, it did not reproduce the problem, only `4` is output.
(Of course, each time I write, the number increases by 4.)

Could you tell me your config for this plugin, please?

**Comment by cappyzawa** [comment]
I've reproduced it!
I only had one `disable` in my config, so it happened to work.

**Comment by cappyzawa** [comment]
This problem should have been fixed by https://github.com/cappyzawa/trim.nvim/commit/bd1565207bd0ac211240641322cfaf70253bc3d5.

Could you update this plugin and test this again? 🙏

**Comment by vzytoi** [comment]
It seems to work!!
For this config :
```
    use {
        'cappyzawa/trim.nvim',
        event = 'BufWritePre',
        config = function()
            require('trim').setup({
                disable = {"json", "javascript", "css"},
                patterns = {
                    [[%s/\s\+$//e]],
                    [[%s/\($\n\s*\)\+\%$//]],
                    [[%s/\%^\n\+//]],
                    [[%s/\(\n\n\)\n\+/\1/]],
                }
            })
        end
    }
```
I have an output of `4`
So it's prefect, have a good day!
