### ISSUE TITLE
[question] is there an option to keep just the empty lines at the end of file

### ISSUE THREAD

**Issue by alexzanderr** [cappyzawa/trim.nvim#7]
i have a file.
i want it to be trimmed.
but i want to keep the exceeding empty lines that are at the end of the file.
is there an option for that?

**Comment by alexzanderr** [comment]
for example, keep all of these lines from 58 to 72, but trim everything else
![image](https://user-images.githubusercontent.com/54772464/134787001-52e1ec02-bbe0-4a5b-9bb6-ef3846041b2a.png)

**Comment by cappyzawa** [comment]
Why don't you use `:noa w` ?

**Comment by alexzanderr** [comment]
it doesnt trim the extra white space on the lines

i've come up with solution:
```lua
    patterns = {
        -- this just trims the whitespace on the lines
        -- its enough
        [[%s/\s\+$//e]],
        -- [[%s/\($\n\s*\)\+\%$//]],
        -- [[%s/\%^\n\+11//]],
        -- [[%s/\(\n\n\)\n\+/\0/]],
    },

```

and its working perfectly
